return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	dependencies = { "williamboman/mason.nvim" },
	event = "VeryLazy",
	opts = {
		ensure_installed = {
			"ast-grep",
			"bash-language-server",
			"biome",
			"black",
			"clang-format",
			"clangd",
			"cpplint",
			"debugpy",
			"dockerfile-language-server",
			"efm",
			"emmet-ls",
			"eslint-lsp",
			"eslint_d",
			"fixjson",
			"flake8",
			"hadolint",
			"intelephense",
			"json-lsp",
			"lemminx",
			"lua-language-server",
			"luacheck",
			"powershell-editor-services",
			"prettier",
			"prettierd",
			"pyright",
			"rustfmt",
			"shellcheck",
			"shfmt",
			"solhint",
			"solidity-ls",
			"stylua",
			"tailwindcss-language-server",
			"typescript-language-server",
			"vscode-solidity-server",
		},
		auto_update = true,
		run_on_start = true,
	},
}
