local config = function()
	require("nvim-treesitter.configs").setup({
		indent = {
			enable = true,
		},
		autotag = {
			enable = true,
		},
		ensure_installed = {
			"bash",
			"c",
			"c_sharp",
			"cmake",
			"cpp",
			"css",
			"diff",
			"dockerfile",
			"dot",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"gpg",
			"html",
			"http",
			"java",
			"javascript",
			"jq",
			"jsdoc",
			"json",
			"json5",
			"jsonnet",
			"kotlin",
			"lua",
			"luadoc",
			"make",
			"matlab",
			"meson",
			"nasm",
			"objdump",
			"pascal",
			"passwd",
			"perl",
			"php",
			"phpdoc",
			"powershell",
			"printf",
			"python",
			"regex",
			"ruby",
			"rust",
			"scss",
			"smali",
			"sql",
			"ssh_config",
			"strace",
			"typescript",
			"tsx",
			"typoscript",
			"vim",
			"vimdoc",
			"vue",
			"xcompose",
			"xml",
			"yaml",
		},
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = true,
		},
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-s>",
				node_incremental = "<C-s>",
				scope_incremental = false,
				node_decremental = "<BS>",
			},
		},
	})
end

return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
	config = config,
}
